### ISSUE TITLE
Needs more sounds!

### ISSUE THREAD

**Issue by DavidVine** [avt-its-simple/Magic-DXLink-Configurator#56]

**Comment by DavidVine** [comment]
- dog bark
- cat meow
- horse neigh
- sheep baa
- wolf howl
- rooster crow
- elephant trumpet
- lion roar
- bird chirp
- clown horn (honka honka)

**Comment by DavidVine** [comment]
- whale song
- dolphin click

**Comment by DavidVine** [comment]
- hyena laugh

**Comment by DavidVine** [comment]
- kookaburra laugh
- cow moo

**Comment by jmagic** [comment]
Added a new preference that allows randomization of the sounds folder. Please download v4.0.1

**Comment by DavidVine** [comment]
Needs more cow bell
